### ISSUE TITLE
Support reviewer work hours

### ISSUE THREAD

**Issue by micheletest** [imsky/pull-review#59]
Just an idea -  If we could configure some variant of work hours optionally, then pull review could be used for a multi time zone team, and for part time people. 

```
exampleUser
  slack: exampleUser
  workHoursStart:
  workHoursStop: 
```
