### ISSUE TITLE
Keep failing to get pull request

### ISSUE THREAD

**Issue by antoooks** [imsky/pull-review#68]
Hi, I'm using pull-review in server mode with Hubot, but everytime I trigger the pull-review it always throw this error either it from slack, github, or CLI mode. I'm using my github personal access token as PULL_REVIEW_GITHUB_TOKEN with required permissions (repo, user)

```  pull-review started server on port 9900 +0ms
  pull-review started on https://github.com/myrepo/all/pull/2556 +0ms
  pull-review Error: Failed to get pull request: https://github.com/myrepo/all/pull/2556
  pull-review     at /usr/lib/node_modules/pull-review/src/generate-plan.js:72:13
  pull-review     at process._tickCallback (internal/process/next_tick.js:178:7) +46s
```

The PR is in our private repo.
Can you point out where I should fix this?

**Comment by imsky** [comment]
i can't think of anything obvious. the 46s difference between the start of pull-review and the error suggests to me there may be a network issue (e.g. a timeout, firewall, etc.). can you confirm that you can issue a GitHub API request using your API token with curl or another tool?

**Comment by antoooks** [comment]
@imsky 

Thanks! actually checking via curl validates the token status, and for this case I think mine is expired somehow and I had to regenerate the token. After I regenerated the Personal Access Token, the error was gone.

 I tried again and it threw this:
```
  pull-review started on https://github.com/myrepo/all/pull/2586 +40s
[Tue Oct 02 2018 07:03:34 GMT+0000 (UTC)] ERROR [pull-review] Error: Missing configuration
  at /usr/lib/node_modules/pull-review/src/generate-plan.js:104:15
  at process._tickCallback (internal/process/next_tick.js:178:7)
```

After that I got the same error message again and after I check with curl, Github said that I was rate-limited.

I think it would be nice if we could pinpoint exactly the reason why we get the message. The rate-limited usage and expired token got the same error message. At least I can check it via curl

**Comment by imsky** [comment]
@antoooks do you have a `.pull-review` file in the root of your repo or the `PULL_REVIEW_CONFIG` env var set?

**Comment by antoooks** [comment]
@imsky yes. I cloned this repo only changing the content of .pull-review

```
drwxrwxr-x   7 ubuntu ubuntu   4096 Oct  2 08:39 .
drwxr-xr-x  13 ubuntu ubuntu   4096 Oct  2 07:43 ..
-rw-rw-r--   1 ubuntu ubuntu    748 Sep 28 10:10 app.json
drwxrwxr-x   2 ubuntu ubuntu   4096 Sep 28 10:10 bin
-rw-rw-r--   1 ubuntu ubuntu    326 Sep 28 10:10 Dockerfile
-rw-rw-r--   1 ubuntu ubuntu     23 Sep 28 10:10 .dockerignore
-rw-rw-r--   1 ubuntu ubuntu    155 Sep 28 10:10 .editorconfig
-rw-rw-r--   1 ubuntu ubuntu    799 Sep 28 10:10 .eslintrc.json
drwxrwxr-x   8 ubuntu ubuntu   4096 Sep 28 10:10 .git
-rw-rw-r--   1 ubuntu ubuntu    675 Sep 28 10:10 .gitignore
-rw-rw-r--   1 ubuntu ubuntu   1184 Sep 28 10:10 index.js
-rw-rw-r--   1 ubuntu ubuntu   1055 Sep 28 10:10 LICENSE
drwxrwxr-x 330 ubuntu ubuntu  12288 Oct  1 06:07 node_modules
-rw-rw-r--   1 ubuntu ubuntu   1683 Sep 28 10:10 package.json
-rw-rw-r--   1 ubuntu ubuntu 168079 Oct  1 06:07 package-lock.json
-rw-rw-r--   1 ubuntu ubuntu     14 Sep 28 10:10 Procfile
-rw-rw-r--   1 ubuntu ubuntu   3328 Oct  1 06:18 .pull-review
-rw-rw-r--   1 ubuntu ubuntu  12504 Sep 28 10:10 README.md
drwxrwxr-x   5 ubuntu ubuntu   4096 Oct  2 07:40 src
-rwxrwxr-x   1 ubuntu ubuntu     34 Oct  1 06:08 start
drwxrwxr-x   4 ubuntu ubuntu   4096 Sep 28 10:10 test
-rw-rw-r--   1 ubuntu ubuntu    178 Sep 28 10:10 .travis.yml
```
after I set the PULL_REVIEW_CONFIG different error pops out:

```  pull-review started on https://github.com/myrepo/all/pull/2634 +0ms
[Thu Oct 04 2018 11:56:16 GMT+0000 (UTC)] ERROR [pull-review] Error: Missing or unsupported config version. Supported versions include: 1
  at PullReviewConfig (/usr/lib/node_modules/pull-review/src/models/config.js:20:11)
  at /usr/lib/node_modules/pull-review/src/generate-plan.js:107:16
  at process._tickCallback (internal/process/next_tick.js:178:7)
```

**Comment by antoooks** [comment]
I console logged `input.version` and it says `undefined`

**Comment by imsky** [comment]
could you paste the contents of .pull-review here @antoooks or if it's sensitive, email it to me?

**Comment by antoooks** [comment]
@imsky sure, here you go:

```yaml
---
# pull-review config version (required)
version: 1

# maximum number of files to evaluate per pull request (set to 0 for no limit)
max_files: 5

# minimum number of reviewers to assign and notify for a pull request
min_reviewers: 1

# maximum number of reviewers to assign and notify for a pull request
max_reviewers: 2

# maximum number of files per reviewer (set to 0 for no limit)
max_files_per_reviewer: 0

# maximum number of lines changed per reviewer (set to 0 for no limit)
max_lines_per_reviewer: 0

# if at least a minimum number of reviewers is not found, assign a minimum number of reviewers randomly
assign_min_reviewers_randomly: true

# if the pull request changes code with fewer than a minimum number of authors, add more reviewers if possible (set to 0 to disable)
min_authors_of_changed_files: 0

# minimum number of lines that should be changed to require an additional reviewer when using min_authors_of_changed_files (set to 0 to disable)
min_lines_changed_for_extra_reviewer: 0

# require a user to be listed in the reviewers section in order to be assigned to a pull request
require_notification: true

# list of users and their app-specific usernames
reviewers:
  alpha:
    slack: "alpha"
  beta:
    slack: "beta13"
  charlie:
    slack: "charlie-charlie"

# list of users who will never be notified
#review_blacklist:
#  - charlie

# always assign the following users based on minimatch (glob) patterns
review_path_assignments:
  "**/android/**":
  - alpha
  - beta
  "**/platform/**":
  - charlie

# if more reviewers are required, assign the following users based on minimatch (glob) patterns 
#review_path_fallbacks:
#  app/web/**:
#  - alice
#  app/api/**:
#  - bob
#  app/ops/**:
#  - alice
#  - dee

# list of minimatch (glob) patterns to ignore when getting files from a pull request
#file_blacklist:
#  - app/ignored_*.*

# list of PR labels to either require (whitelist) or forbid (blacklist) in reviews
label_whitelist: []
label_blacklist: ['WIP']

# use review requests instead of assignees to assign reviewers to pull requests
use_review_requests: true
```
